export const GET_WEATHER_DAILY = "GET_WEATHER_DAILY";
export const GET_WEATHER_DAILY_SUCCESS = "GET_WEATHER_DAILY_SUCCESS";
export const GET_WEATHER_DAILY_ERROR = "GET_WEATHER_DAILY_ERROR";
export const GET_WEATHER_BY_GPS = "GET_WEATHER_BY_GPS";
export const GET_WEATHER_BY_GPS_SUCCESS = "GET_WEATHER_BY_GPS_SUCCESS";
export const GET_WEATHER_BY_GPS_ERROR = "GET_WEATHER_BY_GPS_ERROR";
export const GET_WEATHER_BY_COUNTRY = "GET_WEATHER_BY_COUNTRY";
export const GET_WEATHER_BY_COUNTRY_SUCCESS = "GET_WEATHER_BY_COUNTRY_SUCCESS";
export const GET_WEATHER_BY_COUNTRY_ERROR = "GET_WEATHER_BY_COUNTRY_ERROR";

export * from "./weather/actions";
